### ISSUE TITLE
Server freeze when using M-1.6.8-SNAPSHOT on Mohist Server

### ISSUE THREAD

**Issue by speccycy** [Blank038/Fixer#1]
**Server freeze when using M-1.6.8-SNAPSHOT on Mohist Server**

The server has been running for a while. There will be no response or Freeze at all.
I tried testing with Fixer.M-1.6.3-SNAPSHOT The server can work normally. no problem

Server
mohist-1.12.2-280-server

Mod
Pixelmon-1.12.2-8.3.4-server

Plugin
Fixer.M-1.6.8-SNAPSHOT

**Comment by blank038** [comment]
I tried it and it seems okay.  

![](https://image.mc9y.com/2021/12/12/a4fd032961487.png)

**Comment by speccycy** [comment]
Hmm, it takes about 10-20 minutes for the server to freeze.

**Comment by speccycy** [comment]
> I tried it and it seems okay.
> 
> ![](https://camo.githubusercontent.com/e7193f51c7535b2c4219221be758204bfa50fd992d5c01f858f46c0cc252e897/68747470733a2f2f696d6167652e6d6339792e636f6d2f323032312f31322f31322f613466643033323936313438372e706e67)

Hmm, it takes about 10-20 minutes for the server to freeze.
during my test There are more than 20 players on the server.

**Comment by speccycy** [comment]
![image](https://user-images.githubusercontent.com/68125477/145705100-30e4ce36-bc64-4af3-a6c5-7aae159e68d7.png)

After this, the server has no response.

**Comment by blank038** [comment]
> ![image](https://user-images.githubusercontent.com/68125477/145705100-30e4ce36-bc64-4af3-a6c5-7aae159e68d7.png)
> 
> After this, the server has no response.

upload your logs here(https://paste.ubuntu.com/) and give me the url.

**Comment by blank038** [comment]
> 

for safety, you can tell me the URL via Discord(_**Blank038#5916**_) or Email(admin@mc9y.com).
